os:
  - linux

language: php

php:
  - '7.2'

services:
  - mysql
  
before_script:
  - composer self-update
  - composer install --no-interaction
  - pear install pear/PHP_CodeSniffer
  - cp config.travis.php config.php
  
script:
  - vendor/bin/phpunit --testdox
  - phpcs --standard=PSR2 --extensions=php app